# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3858441b762788ea30f6f11f48bde42f243780b907e38c2633699f6e4af28965926660bb72d4ccc17d804afea3e1993d7f0c9d3a5c233084180d9c15252fe9c3

test:
  secret_key_base: 91c554a1fa5e9b1a19c71dee21ce20ffcc0f596aab7d367b01a3032fa6ac559094b94051900754a3897a8aba17ed7ece93ec4c35f46508d71aa2cb3ae18db1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
